environment:
  matrix:
  - PYTHON: C:/Python27-x64
install:
  - ps: Install-Product node 9
  - npm config set msvs_version 2015
  - npm install
test_script:
  - npm run lint
build: off
platform: x64
configuration: Release
before_deploy:
  - npm run pack:win
  - cd dist
  - 7z a Memgame-win32-x64 Memgame-win32-x64.zip
deploy:
  - provider: GitHub
    artifact: dist/Memgame-win32-x64.zip
    on:
      appveyor_repo_tag: true
artifacts:
  - path: dist/Memgame-win32-x64.zip
    name: Memgame-win32-x64
