environment:
  matrix:
  - PYTHON: C:/Python27-x64
cache:
  - node_modules
install:
  - ps: Install-Product node 9
  - npm config set msvs_version 2015
  - npm install
test_script:
  - npm run lint
platform: x64
before_deploy:
  - npm run build:win
deploy:
- provider: GitHub
  artifact: dist/Memgame-win32-x64.zip
  on:
    appveyor_repo_tag: true

